name: DynamicShop
version: 0.0.1
main: com.sinam7.dynamicshop.DynamicShop
description: Shop with dynamic price
author: sinam7
website: https://github.com/sinam7
api-version: 1.19

commands:
  ds:
    description: Your description
    usage: /<command>
