name: DynamicShop
version: 0.1.0
main: com.sinam7.dynamicshop.DynamicShop
description: Shop with dynamic price
author: sinam7
website: https://github.com/sinam7
api-version: 1.19
depend: [Vault]

commands:
  ds:
    description: Your description
    usage: /<command>
